---
- name: Configure RT/PT SOE
  hosts: all
  become: true
  tasks:
  - name: Add deb-src to sources.List
    apt_repository:
      repo: deb-src http://security.ubuntu.com/ubuntu bionic-security universe
      state: present
  - name: Add another deb-src to sources.list
    apt_repository:
      repo: deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-security universe
      state: present
  - name: Get Oracle Java apt keys
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EEA14886
  - name: Add another deb-src to sources.list for Oracle Java
    apt_repository:
      repo: deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main
      state: present
      validate_certs: no
  - name: Yet another thing to get Oracle Java to install silently
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - name: Yet another thing to get Oracle Java to install silently
    shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
  - name: Update Ubuntu Repos
    apt:
      update_cache: yes
  - name: Upgrade Ubuntu Tools
    apt:
      upgrade: yes
  - name: set timezone to US/Eastern
    timezone:
      name: US/Eastern
  - name: Install Base Packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - build-essential
        - expect
        - dkms
        - locate
        - smbclient
        - nfs-common
        - ipmitool
        - postgresql-server-dev-all
        - autossh
        - gcc
        - g++
        - autoconf
        - git-core
        - subversion
        - curl
        - screen
        - vim
        - tmux
        - htop
        - p7zip
        - python-setuptools
        - python-pip
        - python-dev
        - tcptrack
        - tcpdump
        - traceroute
        - nmap
        - zlib1g-dev
        - libssl-dev
        - perl
        - libffi-dev
        - medusa
        - terminator
        - openssl
        - nikto
        - golang-go
        - hping3
        - openvpn
        - unzip
#        - oracle-java8-installer
  - name: PIP Stuff
    pip:
      name: pexpect impacket crackmapexec lxml
  - name: CPAN Stuff
    expect:
      responses:
        (?i)automatically: "yes"
        (?i)local::lib: ""
        (?i)bashrc: "yes"
      timeout: 600
      command: cpan -i LWP::Simple LWP::UserAgent HTML::TagParser URI::Fetch HTTP::Cookies IO::Socket HTML::TableExtract Getopt::Std Net::SNMP NetAddr::IP #Net::SSL
  - name: Install Apache2
    apt:
      name: apache2
      state: latest
    environment:
      RUNLEVEL: 1
  - name: Clone Unicorn (GIT)
    git:
      repo: 'https://github.com/trustedsec/unicorn.git'
      dest: '/opt/unicorn'
      clone: yes
      update: yes
  - name: Clone Empire (GIT)
    git:
      repo: 'https://github.com/EmpireProject/Empire.git'
      dest: '/opt/empire'
      clone: yes
      update: yes
  - name: Configure Empire
    expect:
      chdir: /opt/empire/setup
      command: ./install.sh
      responses:
        (?i)generation: ""
      timeout: 600
  - name: Download Metasploit Framework Installer
    get_url:
      url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
      dest: /opt/msfinstall
  - name: Setup permissions on MSF Installer
    file:
      path: /opt/msfinstall
      mode: 0755
  - name: Install MSF
    shell: ./msfinstall
    args:
      chdir: /opt/
  - name: Configure MSF
    expect:
      command: msfconsole
      responses:
        (?i)database: "yes"
        (?i)msf: "exit"
      timeout: 60
  - name: Delete MSF Installer
    file:
      path: /opt/msfinstall
      state: absent
  - name: Clone Veil (GIT)
    git:
      repo: 'https://github.com/Veil-Framework/Veil.git'
      dest: '/opt/veil'
      clone: yes
      update: yes
#  - name: Configure Veil #this might need to be done from the GUI
#    expect:
#      chdir: /opt/veil/config/
#      command: ./setup.sh --silent --force
#      responses:
#        (?i)Metasploit: ""
#        (?i)msfvenom: /usr/bin/
#      timeout: 600
  - name: Clone sslscan (GIT)
    git:
      repo: 'https://github.com/rbsec/sslscan.git'
      dest: '/opt/sslscan'
      clone: yes
      update: yes
  - name: Configure sslscan
    shell: make static && mv sslscan /usr/bin/
    args:
      chdir: /opt/sslscan/
  - name: Clone Praeda (GIT)
    git:
      repo: 'https://github.com/percx/Praeda.git'
      dest: '/opt/praeda'
      clone: yes
      update: yes
  - name: Clone EyeWitness (GIT)
    git:
      repo: 'https://github.com/ChrisTruncer/EyeWitness.git'
      dest: '/opt/eyewitness'
      clone: yes
      update: yes
  - name: Configure EyeWitness # error during bzip unpacking but seems to still work?
    shell: ./setup.sh
    args:
      chdir: /opt/eyewitness/setup
  - name: Clone Enum4Linux (GIT)
    git:
      repo: 'https://github.com/portcullislabs/enum4linux.git'
      dest: '/opt/enum4linux'
      clone: yes
      update: yes
  - name: Clone PowerSploit (GIT)
    git:
      repo: 'https://github.com/PowerShellMafia/PowerSploit.git'
      dest: '/opt/powershell-scripts/powersploit'
      clone: yes
      update: yes
  - name: Clone Responder (GIT)
    git:
      repo: 'https://github.com/lgandx/Responder.git'
      dest: '/opt/responder'
      clone: yes
      update: yes
  - name: Clone dnsrecon (GIT)
    git:
      repo: 'https://github.com/darkoperator/dnsrecon.git'
      dest: '/opt/OSINT-tools/dnsrecon'
      clone: yes
      update: yes
  - name: Clone theHarvester (GIT)
    git:
      repo: 'https://github.com/laramies/theHarvester.git'
      dest: '/opt/OSINT-tools/theHarvester'
      clone: yes
      update: yes
  - name: Clone nikto (GIT)
    git:
      repo: 'https://github.com/sullo/nikto.git'
      dest: '/opt/nikto'
      clone: yes
      update: yes
  - name: Clone SQLMap (GIT)
    git:
      repo: 'https://github.com/sqlmapproject/sqlmap.git'
      dest: '/opt/sqlmap'
      clone: yes
      update: yes
  - name: Clone Chameleon (GIT)
    git:
      repo: 'https://github.com/mdsecactivebreach/Chameleon.git'
      dest: '/opt/chameleon'
      clone: yes
      update: yes
  - name: Clone domainHunter (GIT)
    git:
      repo: 'https://github.com/minisllc/domainhunter.git'
      dest: '/opt/domainhunter'
      clone: yes
      update: yes
  - name: Clone domainCat (GIT)
    git:
      repo: 'https://github.com/l0gan/domainCat.git'
      dest: '/opt/domainCat'
      clone: yes
      update: yes
  - name: Clone DPAT (GIT)
    git:
      repo: 'https://github.com/clr2of8/DPAT.git'
      dest: '/opt/DPAT'
      clone: yes
      update: yes
  - name: Clone gobuster (GIT)
    git:
      repo: 'https://github.com/OJ/gobuster.git'
      dest: '/opt/gobuster'
      clone: yes
      update: yes
  - name: Configure gobuster
    shell: go get github.com/OJ/gobuster/libgobuster
    args:
      chdir: '/opt/gobuster'
  - name: Configure gobuster
    shell: go get github.com/OJ/gobuster/gobusterdir
    args:
      chdir: '/opt/gobuster'
  - name: Configure gobuster
    shell: go get golang.org/x/crypto/ssh/terminal
    args:
      chdir: '/opt/gobuster'
  - name: Clone LinkScrape (GIT)
    git:
      repo: 'https://github.com/NickSanzotta/linkScrape.git'
      dest: '/opt/OSINT-tools/linkScrape'
      clone: yes
      update: yes
  - name: Clone morphHTA (GIT)
    git:
      repo: 'https://github.com/mdsecactivebreach/morphHTA.git'
      dest: '/opt/morphHTA'
      clone: yes
      update: yes
  - name: Clone UniByAv (GIT)
    git:
      repo: 'https://github.com/Mr-Un1k0d3r/UniByAv.git'
      dest: '/opt/unibyav'
      clone: yes
      update: yes
  - name: Clone sublist3r (GIT)
    git:
      repo: 'https://github.com/aboul3la/Sublist3r.git'
      dest: '/opt/OSINT-tools/sublist3r'
      clone: yes
      update: yes
  - name: Clone usefulShodan (GIT)
    git:
      repo: 'https://github.com/NickSanzotta/usefulShodan.git'
      dest: '/opt/OSINT-tools/usefulShodan'
      clone: yes
      update: yes
  - name: Clone My Scripts (GIT)
    git:
      repo: 'https://github.com/l0gan/PenTestScripts.git'
      dest: '/opt/l0gan/PentestScripts'
      clone: yes
      update: yes
  - name: Clone BloodHound (GIT)
    git:
      repo: 'https://github.com/BloodHoundAD/BloodHound.git'
      dest: '/opt/BloodHound'
      clone: yes
      update: yes
  - name: Grab some wordlists
    git:
      repo: 'https://github.com/danielmiessler/SecLists'
      dest: '/opt/wordlists'
      clone: yes
      update: yes
#  - name: Setup Oracle Java to be primary (for CS)
#    shell: update-java-alternatives -s java-8-oracle
  - name: Setup UFW
    ufw:
      state: enabled
      rule: limit
      port: ssh
      proto: tcp
  - name: Apt Cleanup
    apt:
      autoclean: yes
      autoremove: yes
